
export type Post = {
  id: number;
  image: string;
  title: string;
  category: string;
  subCategory: string;
  hit: number;
  postBy: string;
  releaseDate: string;
  postDate: string;
  language: string;
  status: "Publish" | "Unpublish";
  socialPost: boolean;
};

export const posts: Post[] = [
  {
    id: 1,
    image: "/placeholder.png",
    title: "The Future of AI in Healthcare",
    category: "Technology",
    subCategory: "AI",
    hit: 1250,
    postBy: "John Doe",
    releaseDate: "2023-10-25",
    postDate: "2023-10-24",
    language: "English",
    status: "Publish",
    socialPost: true,
  },
  {
    id: 2,
    image: "/placeholder.png",
    title: "Sustainable Farming Practices",
    category: "Agriculture",
    subCategory: "Organic",
    hit: 850,
    postBy: "Jane Smith",
    releaseDate: "2023-10-26",
    postDate: "2023-10-25",
    language: "Spanish",
    status: "Publish",
    socialPost: false,
  },
  {
    id: 3,
    image: "/placeholder.png",
    title: "Top 10 Travel Destinations for 2024",
    category: "Lifestyle",
    subCategory: "Travel",
    hit: 3200,
    postBy: "Alice Johnson",
    releaseDate: "2023-10-27",
    postDate: "2023-10-26",
    language: "French",
    status: "Unpublish",
    socialPost: true,
  },
  {
      id: 4,
      image: "/placeholder.png",
      title: "Understanding Crypto Markets",
      category: "Business",
      subCategory: "Finance",
      hit: 1500,
      postBy: "Bob Brown",
      releaseDate: "2023-10-28",
      postDate: "2023-10-27",
      language: "English",
      status: "Publish",
      socialPost: false
  },
   {
    id: 5,
    image: "/placeholder.png",
    title: "Healthy Eating Habits",
    category: "Lifestyle",
    subCategory: "Health",
    hit: 900,
    postBy: "Emily Davis",
    releaseDate: "2023-10-29",
    postDate: "2023-10-28",
    language: "English",
    status: "Unpublish",
    socialPost: false,
  },
  {
    id: 6,
    image: "/placeholder.png",
    title: "Social Media Trends 2024",
    category: "Social Media",
    subCategory: "Marketing",
    hit: 2100,
    postBy: "David Wilson",
    releaseDate: "2023-10-30",
    postDate: "2023-10-29",
    language: "English",
    status: "Publish",
    socialPost: true,
  },
  {
    id: 7,
    image: "/placeholder.png",
    title: "Electric Cars Overview",
    category: "Technology",
    subCategory: "Automotive",
    hit: 1800,
    postBy: "Sophia Miller",
    releaseDate: "2023-10-31",
    postDate: "2023-10-30",
    language: "German",
    status: "Publish",
    socialPost: true,
  },
    {
    id: 8,
    image: "/placeholder.png",
    title: "Minimalist Living",
    category: "Lifestyle",
    subCategory: "Home",
    hit: 1100,
    postBy: "Olivia Taylor",
    releaseDate: "2023-11-01",
    postDate: "2023-10-31",
    language: "English",
    status: "Publish",
    socialPost: false,
  },
  {
    id: 9,
    image: "/placeholder.png",
    title: "Space Exploration Updates",
    category: "Science",
    subCategory: "Space",
    hit: 2500,
    postBy: "James Anderson",
    releaseDate: "2023-11-02",
    postDate: "2023-11-01",
    language: "English",
    status: "Unpublish",
    socialPost: true,
  },
  {
    id: 10,
    image: "/placeholder.png",
    title: "Yoga for Beginners",
    category: "Lifestyle",
    subCategory: "Fitness",
    hit: 1300,
    postBy: "Isabella Thomas",
    releaseDate: "2023-11-03",
    postDate: "2023-11-02",
    language: "English",
    status: "Publish",
    socialPost: false,
  },
   {
    id: 11,
    image: "/placeholder.png",
    title: "Advanced React Patterns",
    category: "Technology",
    subCategory: "Development",
    hit: 1600,
    postBy: "William Jackson",
    releaseDate: "2023-11-04",
    postDate: "2023-11-03",
    language: "English",
    status: "Publish",
    socialPost: true,
  },
    {
    id: 12,
    image: "/placeholder.png",
    title: "Global Economics 2024",
    category: "Business",
    subCategory: "Economy",
    hit: 1400,
    postBy: "Mia White",
    releaseDate: "2023-11-05",
    postDate: "2023-11-04",
    language: "English",
    status: "Publish",
    socialPost: false,
  },
   {
    id: 13,
    image: "/placeholder.png",
    title: "Photography 101",
    category: "Art",
    subCategory: "Photography",
    hit: 1000,
    postBy: "Ethan Harris",
    releaseDate: "2023-11-06",
    postDate: "2023-11-05",
    language: "English",
    status: "Unpublish",
    socialPost: true,
  }
];
